---
title: "Schedule"
---

| **Week** |  **Date**   | **Lead Instructor**            |           **Topic**                                                          |                          **Functions introduced**                                                                             |         **Assigned**         |           **Due**       |       **Reading**                         |
| :------- | :---------: | :----------------------------: | :--------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------------------------------------: | :--------------------------: | :---------------------: | :---------------------------------------: |
|     1a   |     3/30/20 |              Joe               |                    Intro to course<br/>Installing software                   |                                                                                                                               | Final <br/>Get to know data  |                         | [HML Ch. 1](https://bradleyboehmke.github.io/HOML/intro.html) |
|     1b   |     4/1/20  |             Daniel             |  [Inference vs. Prediction<br/>Estimating $f$<br/>Regression vs Classification](slides/w1p2-inf-v-pred.html)|                                                                                                |                              |                         |       APM: Ch. 1<br/>ISLR: Ch. 2.1        |
|     2a   |     4/6/20  |              Joe               |         Bias-variance tradeoff<br/>test set<br/>k-fold CV (& repeats)        |  `initial_split`<br/>`train()`<br/>`test()`<br/>`vfold_cv()` & others                                                         |                              |                         |      ISLR: Ch. 2.2<br/>ISLR: Ch 5.1       |
|     2b   |     4/8/20  |              Joe               |  Lab 1: <br/>Resampling 							                                       |                                                                                                                       	       |           Lab 1              |                         |                                           |
|     3a   |     4/13/20 |             Daniel             |                  Variable Selection & <br/>Model performance                 |  Choose “model function”<br/>`set_engine()`<br/>`set_mode()`<br/>`fit_resamples()`<br/>`collect_metrics()`<br/>`select_best()`|                              |      Lab 1              | ISLR: Ch. 6.1<br/> APM: Ch. 5<br/>APM: Ch. 11 |
|     3b   |     4/15/20 |             Daniel             |            Lab 2: <br/>Building a predictive lm and Measuring performance    |                                                                                                                        	     |           Lab 2              |                         | [HML: Ch. 4](https://bradleyboehmke.github.io/HOML/linear-regression.html) <br/>APM: Ch. 6.1 & 6.2 |
|     4a   |     4/20/20 |              Joe               |                  Extending lm: Ridge, Lasso, Elastic net                     |  New arguments to `linear_reg()`<br/>`metric_set()`<br/>`tune_grid()`<br/>`grid_regular()`<br/>`show_best()`                  |                              |      Lab 2              | [HML: Ch. 6](https://bradleyboehmke.github.io/HOML/regularized-regression.html) <br/>APM: Ch. 6.4 |
|     4b   |     4/22/20 |              Joe               |                         Lab 3:<br/>Penalized Regression                      |                                                                                                                             	 |           Lab 3              |                         |                                           |
|     5a   |     4/27/20 |             Daniel             |                              Feature engineering                             |  [{recipes}](https://tidymodels.github.io/recipes/)                                                                           |                              |      Lab 3              | [FE: Ch. 1](http://www.feat.engineering/intro-intro.html)<br/> [HML: Ch. 3](https://bradleyboehmke.github.io/HOML/engineering.html) |
|     5b   |     4/29/20 |             Daniel             |              Lab 4: <br/>Feature Engineering (Dimension Reduction)           |                                                                                                                               |           Lab 4              |    Preliminary Fit 1    |                                           |
|     6a   |     5/4/20  |              Joe               |                             *K*-nearest neighbor                             |       `nearest_neighbor()`<br/>`grid_max_entropy()`<br/>`autoplot()`                                                          |                              |      Lab 4              | [HML: Ch. 8](https://bradleyboehmke.github.io/HOML/knn.html) |
|     6b   |     5/6/20  |              Joe               |                  Lab 5: <br/> *K*NN                                          |                                                                                                                               |           Lab 5              |                         |                                           |
|     7a   |     5/11/20 |             Daniel             |                                Decision trees                                |                                                                                                                               |                              |      Lab 5              |[HML: Ch. 9](https://bradleyboehmke.github.io/HOML/DT.html) |
|     7b   |     5/13/20 |             Daniel             |                                 Bagged trees                                 |                                                                                                                               |                              |                         |[HML: Ch. 10](https://bradleyboehmke.github.io/HOML/bagging.html) |
|     8a   |     5/18/20 |              Joe               |                                Random forests                                |                                                                                                                               |                              |                         |[HML: Ch. 11 ](https://bradleyboehmke.github.io/HOML/random-forest.html) |
|     8b   |     5/20/20 |              Joe               |             Lab 6: <br/> Ensemble Methods                                    |                                                                                                                               |           Lab 6              |    Preliminary Fit 2    |                                           |
|     9a   |     5/25/20 |             Daniel             |                                 Boosted trees                                |                                                                                                                               |                              |      Lab 6              |[HML Ch. 12](https://bradleyboehmke.github.io/HOML/gbm.html) |
|     9b   |     5/27/20 |                                |                                   Work Day                                   |                                                                                                                               |                              |                         |                                           |
|     10a  |     6/1/20  |             Daniel             |                             Advanced topics in ML                            |                                                                                                                               |                              |                         |                [HML Ch. 13](https://bradleyboehmke.github.io/HOML/deep-learning.html) & [15](https://bradleyboehmke.github.io/HOML/stacking.html) |
|     10b  |     6/3/20  | Guest Lecture: Sondra Stegenga |                                   ML Ethics                                  |                                                                                                                               |                              |                         |[Floridi & Taddeo (2016)](https://royalsocietypublishing.org/doi/full/10.1098/rsta.2016.0360) |
| Finals Week | 6/10/20  |                                |                                                                              |                                                                                                                               |                              | Final Project           |                                           |